#pragma once
#define BINDING_ALBEDO 0
#define BINDING_NORMAL 1
#define BINDING_MATERIAL 2
#define BINDING_DEBUG 3
#define BINDING_DOWNSAMPLE_DEPTH 4
#define BINDING_DEPTH 5
#define BINDING_IRRADIANCE 6
#define BINDING_PREFILTEREDENV 7
#define BINDING_BRDFLUT 8
#define BINDING_RANDOM 9
#define BINDING_COUNT 10